In [10]:
import pandas as pd
import os

db = pd.DataFrame({"lines in text": ["erda", "capodoglio", "cazzo"], "words": ["11:18", "22:45", "74:98"], "values":[1,2,3]})
db

  lines in text  words  values
0          erda  11:18       1
1    capodoglio  22:45       2
2         cazzo  74:98       3

In [15]:
bereshit_address = "http://localhost:8888/edit/PycharmProjects/gimatria/utilities/Bereshit_lines.txt"

In [16]:
selected_books=[bereshit_address]

In [40]:
import numpy as np
def dic_conv(argument):
    switcher = {"א": 1,
                        "ב": 2,
                        "ג": 3,
                        "ד": 4,
                        "ה": 5,
                        "ו": 6,
                        "ז": 7,
                        "ח": 8,
                        "ט": 9,
                        "י": 10,
                        "כ": 20,
                        "ך": 20,
                        "ל": 30,
                        "מ": 40,
                        "ם": 40,
                        "נ": 50,
                        "ן": 50,
                        "ס": 60,
                        "ע": 70,
                        "פ": 80,
                        "ף": 80,
                        "צ": 90,
                        "ץ": 90,
                        "ק": 100,
                        "ר": 200,
                        "ש": 300,
                        "ת": 400}
    return switcher.get(argument, lambda: "invalid character: use only hebrew characters.")


def convert_list(word_list):
    gim_word = []
    gim_word_list = []
    for word in word_list:
        if word.isdigit():
            gim_word.append(int(word))
            gim_word.append(0)
        else:
            for i in word:
                j = dic_conv(i)
                gim_word.append(int(j))
            summa_parziale = sum(gim_word)
            # print(summa_parziale, "somma parziale")
            gim_word_list.append(summa_parziale)
            gim_word = []
    summa = gim_word_list
    # print(summa, "summa")
    return summa

super_word_index = []
super_booklist = []
db = pd.DataFrame()
index_list_sup = []
splitted_list_sup = []
values_converted_sup = []    
for selected_book in selected_books:
    my_Bible_book = open("Bereshit_lines.txt", "r")
    my_bb_lines = my_Bible_book.readlines()
    
    for my_bb_line in my_bb_lines:
        splitted_line = my_bb_line.split()
        single_index = str(splitted_line[0]).replace("[", "").replace("]", "").replace("\u200f", "")
        
        index_list = [str(splitted_line[0]).replace("[", "").replace("]", "").replace("\u200f", "")]*len(splitted_line[1:])
        splitted_list = splitted_line[1:]
        values_converted = convert_list(splitted_list)
        index_list_sup.extend(index_list)
        splitted_list_sup.extend(splitted_list)
        values_converted_sup.extend(values_converted)
        
        
    db["values"] = values_converted_sup
    db["words"] = splitted_list_sup
    db["line address"] = index_list_sup
    db.set_index("line address")
    
print(db.head(), db.count(), db[db["values"] == 246])

   values   words line address
0     913  בראשית          1:1
1     203     ברא          1:1
2      86   אלהים          1:1
3     401      את          1:1
4     395   השמים          1:1 values          20613
words           20613
line address    20613
dtype: int64        values  words line address
179       246  להאיר         1:15
207       246  להאיר         1:17
236       246  יעופף         1:20
3946      246   מראה        12:11
5083      246   אמרה        16:13
6541      246   אמרה         20:5
6954      246   אמרה        21:16
8082      246   מראה        24:16
9260      246   מראה         26:7
9692      246   אמרה         27:6
9701      246   מדבר         27:6
10698     246   מדבר         29:9
10822     246   מראה        29:17
10996     246   אמרה        29:32
11485     246  כדברך        30:34
12008     246   מדבר        31:29
12515     246   האמר        32:10
15394     246   מראה         39:6
15970     246   מראה         41:2
15984     246   מראה         41:3
19509     246  כדברך        47:30